### ISSUE TITLE
I want to be able to stop the process

### ISSUE THREAD

**Issue by tgraveleau** [julhenry/cleanmymattermost#12]
When I start the update with the button at the last step, I can still click on the button (the loader has replaced the label) but nothing happen.
I want to be able to stop the process.
Moreover, the button should be disabled when it has the loader inside.

My suggestion is :
* Put the loader after the button, just aside it
* Don't change the label of the button while the page is loading but disable it
* At the last step, don't disable the button but change its label for "Stop here" or something like that. On click, it stop the process.

I appreciate any other suggestion or advice.

**Comment by a-leblond** [comment]
I prefer the last suggestion, it's more user friendly and after clicking "Stop" we should be able to resume the process where it was stopped.

**Comment by tgraveleau** [comment]
Well, actually, I suggested to do all points, not only one ^^
I'm putting the loader outside. I'm disabling the buttons. I'm implementing the stop button.

**Comment by a-leblond** [comment]
Ahh didn't notice the loader on each step, I thought you were refering only to the last step. So the 3 points make sense to me. 👍
